GET http://localhost:4000/api/read/book

###

GET http://localhost:4000/api/read/book/9781449331815

###

POST http://localhost:4000/api/create/book
content-type: application/json

{
    "isbn": "9781449331815",
    "title": "Learning JavaScript Design Patterns",
    "subtitle": "A JavaScript and jQuery Developer's Guide",
    "categories": "1,2,3",
    "author": 1,
    "publisher": 1,
    "published": "2012-07-01T07:00:00.000Z",
    "pages": 250,
    "description": "With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
    "website": "http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/"
}

###

PUT http://localhost:4000/api/update/book
content-type: application/json

{
    "isbn": "9781449331815",
    "publisher": 2,
    "pages": 2540
}